main: "${project.groupId}.${project.artifactId}.BukkitMain"
name: "${project.name}"
version: "${project.version}"
author: "Brutus"
depend: [PubSub]

commands:
    networkstatus:
        permission: serverclusters.commands.networkstatus
        permission-message: Unknown command. Please try again.
        aliases: [ns]